
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Tags: /tags
  Selfie: /selfie

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/toggle_nav.js
- /js/scroll.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css