
# html lang
language: zh-Hans

# main menu navigation
menu:
  Home: /
  About: /about/about
  Tags: /tags

# customize your terminal panel
terminal:
  #Home
  Blog:
    motto: 
      typ: string
      val: Using strength, being weak. Being the root of the world.
    author: 
      typ: string
      val: cifangyiquan
    more:
      typ: link
      val: http://cifangyiquan.coding.me
      url: http://cifangyiquan.coding.me
  #About
  cifangyiquan:
    locations: 
      typ: string
      val: Beijng
    interests:
      typ: array
      val: coding acg 
    github:
      typ: link
      val: github.com/hd264
      url: https://github.com/hd264
  #Tags
  Tags:
  #Post
  Post:

#social media
#name: url
social:
  # github: https://github.com/hd264
  
# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/nav.js
- /js/scroll.js
- /js/index.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css