
# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Tags: /tags
  Selfie: /selfie

# customize your terminal panel
terminal:
  Blog:
    purpose: 
      typ: string
      val: Sharing something interesting in my limited life.
    author: 
      typ: string
      val: LazySheep
    more:
      typ: link
      val: check here
      url: https://github.com/lazysheep666/lazysheep666.github.io
  Sheep:
    locations: 
      typ: array
      val: Beijng Chongqing
    education:
      typ: string
      val: BUPT
    interests:
      typ: array
      val: coding basketball sleeping reading
    github:
      typ: link
      val: github.com/lazysheep666
      url: https://github.com/lazysheep666
    mail: 
      typ: link
      val: mail to Sheep
      url: mailto:714201376@qq.com
  Tags:
  Selfie:

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
scripts:
- /js/toggle_nav.js
- /js/scroll.js
# the third-party loaded in the head
third_party:
  js:
    jquery: /js/third-party/jquery.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 
  css:
    font-awsome: https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css